# ContextCore Project Context
# This file defines project metadata that Claude Code uses for context-aware assistance
# Updated: 2026-01-21

project:
  id: "contextcore"
  name: "ContextCore"
  epic: "PROJECT-O11Y"
  description: |
    Project management observability framework modeling tasks as OpenTelemetry spans.
    Dual-telemetry architecture: spans to Tempo (hierarchy, timing, TraceQL) and
    structured logs to Loki (events, status changes, metrics derivation via recording rules).

# Current implementation status
status:
  phase: "Phase 4 - OTel GenAI Alignment"
  recentChanges:
    - "OTel GenAI semantic convention alignment (dual-emit agent.* + gen_ai.*)"
    - "HistoricalTaskTracker now emits both spans AND logs for demo data"
    - "Exporter supports pushing logs to Loki via push API"
    - "Portfolio dashboard updated with 11 dashboards provisioned (6 core + 5 expansion)"
    - "Dashboard $project variables fixed to default to 'contextcore'"
    - "Identified task tracking vs deliverable validation gap"
    - "Added Fox (Waagosh) alert automation dashboard"
    - "Added Beaver (Amik) lead contractor progress dashboard"
    - "Established Dependency Manifest Pattern for tracking external dependencies"
    - "Added Infinity datasource for Rabbit API integration"
  nextSteps:
    - "Verify demo data appears in both Tempo and Loki"
    - "Create agent insights dashboard for gen_ai.* attributes"
    - "Implement Loki recording rules for task_percent_complete metrics"
    - "Add deliverable validation to task completion criteria"
    - "Add CI validation for dependency manifests"
    - "Create pre-commit hook for dependency scanning"

business:
  criticality: critical
  owner: "observability-team"
  value: "Eliminates manual status reporting by deriving project health from artifact metadata"
  costCenter: "platform-engineering"

  risks:
    - risk: "OTLP exporter failure blocks project health reporting"
      priority: P1
      mitigation: "Implement fallback to file-based persistence with async retry"
      scope:
        - "src/contextcore/tracker.py"
        - "src/contextcore/state.py"

    - risk: "Kubernetes controller restart loses in-flight span state"
      priority: P1
      mitigation: "Persist span state to ConfigMap before OTLP export"
      scope:
        - "src/contextcore/state.py"
        - "src/contextcore/detector.py"

    - risk: "Agent insight queries exceed latency budget"
      priority: P2
      mitigation: "Add caching layer with 5-minute TTL for insight queries"
      scope:
        - "src/contextcore/agent/insights.py"

    - risk: "VSCode extension activation delays editor startup"
      priority: P2
      mitigation: "Lazy-load Kubernetes provider, defer context loading"
      scope:
        - "extensions/vscode/**"

    - risk: "Dashboard provisioning fails silently on Grafana API errors"
      priority: P3
      mitigation: "Add retry logic and user-visible error notifications"
      scope:
        - "src/contextcore/dashboards/provisioner.py"

    - risk: "Portfolio dashboard shows no data without both Loki AND Tempo data"
      priority: P2
      mitigation: "Demo generator now emits dual telemetry (spans + logs)"
      scope:
        - "src/contextcore/demo/generator.py"
        - "src/contextcore/demo/exporter.py"

    - risk: "Metrics derivation requires Loki recording rules not yet deployed"
      priority: P2
      mitigation: "Document recording rules in semantic-conventions.md, add provisioning"
      scope:
        - "docs/semantic-conventions.md"
        - "loki/rules/"

    - risk: "Task 'done' status tracks execution, not deliverable completion"
      priority: P2
      mitigation: |
        Task tracking captures workflow execution status (ran successfully) but not
        whether expected deliverables were produced. Add deliverable validation:
        1. Post-completion hooks that verify expected outputs exist
        2. Span events with deliverable checksums or existence checks
        3. Dashboard panels showing tasks vs verified deliverables
      scope:
        - "src/contextcore/tracker.py"
        - "docs/semantic-conventions.md"
      lesson: |
        Discovered via phase tasks that marked 11 tasks as 'done' in Tempo but
        expected document sections were not created. Execution ≠ completion.

    - risk: "Implicit dependencies cause deployment failures"
      priority: P2
      mitigation: |
        Dependencies defined in design artifacts (dashboards, configs) must be
        explicitly declared in manifests and validated at multiple checkpoints:
        1. Dependency manifests at component level (grafana/provisioning/dashboards/dependencies.yaml)
        2. Pre-commit validation for new dependency references
        3. CI pipeline validation of manifest completeness
        4. Runtime verification via contextcore install verify
        See docs/DEPENDENCY_MANIFEST_PATTERN.md for full pattern.
      scope:
        - "grafana/provisioning/dashboards/dependencies.yaml"
        - "docs/DEPENDENCY_MANIFEST_PATTERN.md"
        - "scripts/validate_dependencies.py"
      lesson: |
        Discovered when loading Beaver dashboard that referenced yesoreyeram-infinity-datasource
        plugin not configured in Grafana. Design-time dependencies must flow to deploy-time.
      pattern: "docs/DEPENDENCY_MANIFEST_PATTERN.md"
      antipattern: "Scattered implicit dependencies discovered only at deploy time"

requirements:
  availability: "99.9%"
  latencyP99: "500ms"
  latencyP50: "100ms"
  dataRetention: "30 days"
  throughput: "1000 spans/second"
  errorBudget: "0.1%"

design:
  adr: "docs/adr/001-tasks-as-spans.md"
  doc: "docs/CLAUDE-full.md"
  apiContract: "docs/semantic-conventions.md"
  agentProtocol: "docs/agent-communication-protocol.md"
  otelGenaiMigration: "docs/OTEL_GENAI_MIGRATION_GUIDE.md"
  otelGenaiGapAnalysis: "docs/OTEL_GENAI_GAP_ANALYSIS.md"
  expansionPacks: "docs/EXPANSION_PACKS.md"
  namingConvention: "docs/NAMING_CONVENTION.md"
  dependencyManifest: "docs/DEPENDENCY_MANIFEST_PATTERN.md"

# Expansion Pack Ecosystem
# Animal names with Anishinaabe (Ojibwe) translations honoring Michigan's indigenous peoples
ecosystem:
  namingConvention: "animal-anishinaabe"
  packages:
    - name: "contextcore"
      animal: "Spider"
      anishinaabe: "Asabikeshiinh"
      meaning: "Little net maker"
      purpose: "Core framework—tasks as spans, agent insights, observability"
      status: "beta"
    - name: "contextcore-rabbit"
      animal: "Rabbit"
      anishinaabe: "Waabooz"
      purpose: "Core alert automation framework (webhooks, parsers, actions)"
      status: "beta"
      formerName: "Hermes"
    - name: "contextcore-fox"
      animal: "Fox"
      anishinaabe: "Waagosh"
      purpose: "ContextCore integration for alert automation (context enrichment)"
      status: "beta"
      dependsOn: ["contextcore-rabbit"]
    - name: "contextcore-coyote"
      animal: "Coyote"
      anishinaabe: "Wiisagi-ma'iingan"
      purpose: "Multi-agent incident resolution pipeline"
      status: "beta"
      formerName: "agent-pipeline"
    - name: "contextcore-beaver"
      animal: "Beaver"
      anishinaabe: "Amik"
      purpose: "LLM provider abstraction with cost tracking and token accounting"
      status: "beta"
      formerName: "startd8"
    - name: "contextcore-squirrel"
      animal: "Squirrel"
      anishinaabe: "Ajidamoo"
      purpose: "Skills library for token-efficient agent discovery and knowledge storage"
      status: "beta"
      formerName: "contextcore-skills"
    - name: "contextcore-owl"
      animal: "Owl"
      anishinaabe: "Gookooko'oo"
      meaning: "Owl (watchful, excellent vision)"
      purpose: "Unified Grafana plugin package (workflow triggers, chat panels, datasources)"
      status: "beta"
      formerName: "contextcore-grafana"
      dependsOn: ["contextcore-beaver"]  # Optional, for scaffold script LLM generation

# Dashboards (11 total, provisioned to Grafana)
# Dependencies declared in: grafana/provisioning/dashboards/dependencies.yaml
dashboards:
  dependencyManifest: "grafana/provisioning/dashboards/dependencies.yaml"
  provisioned:
    # Core dashboards
    - id: "contextcore-portfolio"
      name: "Project Portfolio Overview"
      file: "grafana/provisioning/dashboards/json/portfolio.json"
      datasources: ["Loki", "mimir"]
    - id: "contextcore-installation"
      name: "Installation Verification"
      file: "grafana/provisioning/dashboards/json/installation.json"
      datasources: ["Prometheus/mimir"]
    - id: "contextcore-value"
      name: "Value Capabilities Explorer"
      file: "grafana/provisioning/dashboards/json/value-capabilities.json"
      datasources: ["Tempo"]
    - id: "contextcore-progress"
      name: "Project Progress"
      file: "grafana/provisioning/dashboards/json/project-progress.json"
      datasources: ["Tempo"]
    - id: "contextcore-sprint"
      name: "Sprint Metrics"
      file: "grafana/provisioning/dashboards/json/sprint-metrics.json"
      datasources: ["Tempo"]
    - id: "contextcore-ops"
      name: "Project Operations"
      file: "grafana/provisioning/dashboards/json/project-operations.json"
      datasources: ["Tempo"]
    # Expansion pack dashboards
    - id: "fox-alert-automation"
      name: "Fox Alert Automation"
      file: "grafana/provisioning/dashboards/json/fox-alert-automation.json"
      datasources: ["Tempo", "Loki", "mimir"]
      expansionPack: "contextcore-fox"
    - id: "beaver-lead-contractor"
      name: "Lead Contractor Progress"
      file: "grafana/provisioning/dashboards/json/beaver-lead-contractor-progress.json"
      datasources: ["Tempo", "mimir"]
      expansionPack: "contextcore-beaver"
    - id: "skills-browser"
      name: "Skills Browser"
      file: "grafana/provisioning/dashboards/json/skills-browser.json"
      datasources: ["Tempo"]
      expansionPack: "contextcore-squirrel"
    - id: "workflow"
      name: "Workflow Manager"
      file: "grafana/provisioning/dashboards/json/workflow.json"
      datasources: ["Tempo"]
      expansionPack: "contextcore-rabbit"
    - id: "agent-trigger"
      name: "Agent Trigger"
      file: "grafana/provisioning/dashboards/json/agent-trigger.json"
      datasources: ["Loki"]
  needed:
    - "Agent Insights Dashboard (gen_ai.* attributes)"
    - "Agent Handoffs Dashboard (handoff.* + gen_ai.tool.*)"

targets:
  - kind: Deployment
    name: contextcore-controller
    namespace: contextcore-system
  - kind: Service
    name: contextcore-api
    namespace: contextcore-system

designDecisions:
  - decision: "Model tasks as OpenTelemetry spans for unified observability"
    confidence: 0.95
    rationale: "Spans have same structure as tasks (start, end, status, hierarchy)"

  - decision: "Export via OTLP for vendor independence"
    confidence: 0.92
    rationale: "Avoid lock-in, works with any OTLP-compatible backend"

  - decision: "Use Pydantic v2 for CRD schema validation"
    confidence: 0.88
    rationale: "Strict validation, good error messages, Python-native"

  - decision: "Store agent insights as spans in Tempo"
    confidence: 0.85
    rationale: "Reuse existing infrastructure, enables time-range queries"

  - decision: "Dual-emit spans (Tempo) AND logs (Loki) for complete observability"
    confidence: 0.90
    rationale: |
      Portfolio dashboard requires both: Tempo for task hierarchy/timing queries,
      Loki for event streams and metrics derivation via recording rules.
      Mimir metrics are derived from Loki logs, not directly emitted.

  - decision: "Align with OTel GenAI semantic conventions via dual-emit"
    confidence: 0.88
    rationale: |
      Emit both agent.* (legacy) and gen_ai.* (OTel standard) attributes during
      migration period. Controlled by CONTEXTCORE_OTEL_MODE env var.
      See docs/OTEL_GENAI_MIGRATION_GUIDE.md for migration path.

  - decision: "Demo generator emits both spans and logs"
    confidence: 0.92
    rationale: |
      HistoricalTaskTracker now uses HistoricalTaskLogger to emit logs with
      historical timestamps alongside spans. Enables full dashboard testing.

  - decision: "Explicit dependency manifests for external dependencies"
    confidence: 0.90
    rationale: |
      Dependencies defined in design artifacts (Grafana plugins in dashboards, external
      APIs in configs) must be explicitly declared in component-level manifests and
      validated at design, build, and deploy time. Prevents "works on my machine" failures.
      See docs/DEPENDENCY_MANIFEST_PATTERN.md for full specification.
